name: Test Async Python Paystack Package

on:
  pull_request:
    branches: [ "main" ]

env:
    PAYSTACK_BASE_URL: ${{ secrets.PAYSTACK_BASE_URL }}
    PAYSTACK_SECRET_KEY: ${{ secrets.PAYSTACK_SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest